name: Leonardo CI
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20' # Escolha a versão do Node.js que se adequa ao seu projeto
      
      - name: Reinstalar bcrypt na pasta api
        run: |
          cd api
          npm uninstall bcrypt
          npm install bcrypt
      
      - name: Instalar lodash.debounce na pasta api
        run: |
          cd my-app
          npm install lodash.debounce
      
      - name: Instalar next.js na pasta my-app
        run: |
          cd my-app
          npm install next

      - name: Instalar react-currency-input-field na pasta my-app
        run: |
          cd my-app
          npm install react-currency-input-field
      
      - name: Build da aplicação next.js na pasta my-app
        run: |
          cd my-app
          npm run build
      
      - name: Deploy para meu hosting
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
          TARGET: ${{ secrets.TARGET }}